### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by henryruhs** [AlexMelov/FullStackApp#32]
- The readme is missing actual commands to get things installed.

```
npm install
```

- What does the developer to setup (database etc.) the application?
- Show example of `.env`file:

```
DB_URL=
```

- Tell developers how to actuall start the application.

```
npm run start:dev
```

**Comment by henryruhs** [comment]
That issue is not solved

**Comment by AlexMelov** [comment]
I think it's better this time, if it's not, please can you give me more detail information what is missing, I check other projects on github and your github repositories, and I think I'm close.
